# ── Prefix Key ──────────────────────────
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# ── General Settings ─────────────────────
set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g pane-border-lines "double"
set -s escape-time 10

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# ── TPM Plugin Manager ───────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# ── Terminal Colors ──────────────────────
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ── Theme (via TPM) ──────────────────────
set -g @catppuccin_flavor 'frappe'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"
set -g @catppuccin_window_current_text " #{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

set -g @plugin 'catppuccin/tmux'

# ── Status Bar ────────────────────────────
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag  status-right "#{E:@catppuccin_status_session}"

# ── TPM Plugin Manager ───────────────────
run '~/.config/tmux/plugins/tpm/tpm'
