input type:pointer {
	accel_profile adaptive
	pointer_accel 0
}

input type:keyboard {
	xkb_layout "us,ru"
	xkb_options ctrl:nocaps,altwin:swap_lalt_lwin,grp:win_space_toggle
}

input type:touchpad {
	dwt enabled
	tap enabled
	natural_scroll enabled
}

input 2:10:TPPS/2_Elan_TrackPoint {
  accel_profile adaptive
	pointer_accel -0.65
}
