theme = "catppuccin_frappe"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = false
bufferline = "never"
popup-border = "all"
end-of-line-diagnostics = "disable"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.soft-wrap]
enable = true
